
# This config file facilitates automated static analysis on lgtm.com.
path_classifiers:
  test:
    - exclude: /
    - "src/*hpp"
    - "examples/*cc"
    
extraction:
  cpp:
    prepare:
      packages:
      # Explicitly install known packages.
      - "git"
      - "cmake"
      - "make"
      - "g++"
      - "rsync"
    after_prepare:
    # Create an accessible installation root directory.
    - "mkdir -pv $LGTM_WORKSPACE/placeholder_root/{include,lib,bin,share}"
    # Test installation script by Installing headers to an accessible and user-writeable directory.
    - "cd $LGTM_SRC"
    - "./compile_and_install.sh -u -i $LGTM_WORKSPACE/placeholder_root -b build"
    index:
      # Compile the examples to provide an analysis entrypoint.
      build_command: "cd examples/ && CPLUS_INCLUDE_PATH=$LGTM_SRC/src ./compile.sh"      
